#ifndef GB_MEMORY_MAP_H
#define GB_MEMORY_MAP_H

#define GB_BANK_00_START 0x0000
#define GB_BANK_00_END 0x3FFF
#define GB_BANK_01_START 0x4000
#define GB_BANK_NN_END 0x7FFF

#define GB_VRAM_START 0x8000
#define GB_VRAM_END 0x9FFF

#define GB_ERAM_START 0xA000
#define GB_ERAM_END 0xBFFF

#define GB_WRAM_START 0XC000
#define GB_WRAM_END 0xCFFF

#define GB_WRAM2_START 0XD000
#define GB_WRAM2_END 0xDFFF

#define GB_OAM_START 0XFE00
#define GB_OAM_END 0XFE9F

#define GB_IO_START 0xFF00
#define GB_IO_END 0xFF7F

#define GB_HRAM_START 0xFF80
#define GB_HRAM_END 0xFFFE

#define GB_IE_REGISTER 0xFFFF

#endif