#ifndef GB_PALLETE_H
#define GB_PALLETE_H

//White, light gray, darkGray, Black
// TESTING PALLETE AND EXPERIMENTAL HEADER...
#define GB_DEFAULT_PALLETE_0 0xFFFFFF
#define GB_DEFAULT_PALLETE_1 0xAAAAAA
#define GB_DEFAULT_PALLETE_2 0x555555
#define GB_DEFAULT_PALLETE_3 0x000000

#endif